subjects.page_size=10
topics.page_size=10
resource_types.page_size=10
resource_tags.page_size=10
courses.page_size=9
enrollments.page_size=10
resources.page_size=9
quizzes.page_size=10
users.page_size=10
payments.page_size=10
forum_categories.page_size=10
forum_threads.page_size=10
forum_posts.page_size=10
chat_rooms.page_size=10
chat_participants.page_size=10
chat_messages.page_size=20

